db:
    image: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
annotationhub:
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
        MYSQL_REMOTE_PASSWORD: 
    image: "dtenenba/annotationhubserver"
    links:
     - "db"
    ports:
     - "3000:3000"
    volumes:
     - "./AnnotationHubServer3.0:/AnnotationHubServer3.0"
     - "./data:/data"
    command:  "/tmp/start.sh"

